### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [tisimst/hersheyfonts#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert specific fonts (Persian ) to Hershey fonts?

**Comment by tisimst** [comment]
I'm afraid I don't. "Hershey" fonts glyph designs specifically encoded as (x0,y0)->(x1,y1) line segments, which I then "traced" using functionality in FontForge. As far as I know, A. V. Hershey never created designs for Persian glyphs. Sorry I can't be more helpful.
